title: Champlemy Wiki
description: Wiki for Champlemy
theme: just-the-docs

url: https://aaronmee.github.io/champlemy-wiki

aux_links:
  Template Repository: https://github.com/aaronmee/champlemy-wiki
